---
peers:
    - aenode://pp_28uQUgsPcsy7TQwnRxhF8GMKU4ykFLKsgf4TwDwPMNaSCXwWV8@node2:3015
    - aenode://pp_Dxq41rJN33j26MLqryvh7AnhuZywefWKEPBiiYu2Da2vDWLBq@node3:3015

http:
    external:
        port: 3013
    internal:
        listen_address: 0.0.0.0

websocket:
    internal:
        listen_address: 0.0.0.0

keys:
    password: "top secret"
    dir: ./keys

chain:
    persist: true

mining:
    autostart: true
    beneficiary: "ak_25MZX3BXYP32YDPGWsJqYZ6CgWnqD93VdpCYaTk6KsThEbeFJX"
    cuckoo:
        miner:
            executable: mean16s-generic
            extra_args: ""
            node_bits: 16
